version: '3'
services:
  nextjs:
    container_name: nextjs102_amazon
    build:
      context: ..
      dockerfile: .docker_102/Dockerfile
    ports:
      - "48001:3000"
    volumes:
      - ../app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      # Các biến môi trường để kết nối tới PostgreSQL
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: db_amazon_shop
      POSTGRES_USER: user_amazon
      POSTGRES_PASSWORD: 123456
    networks:
      - nextjs102

  postgres:
    image: postgres
    container_name: postgres102_amazon
    environment:
      POSTGRES_DB: db_amazon_shop
      POSTGRES_USER: user_amazon
      POSTGRES_PASSWORD: 123456
    ports:
      - "5492:5432"  # Mở cổng 5432 để có thể kết nối từ bên ngoài nếu cần
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Lưu trữ dữ liệu
    networks:
      - nextjs102

volumes:
  postgres_data:

networks:
  nextjs102:
