version: '3'
services:
  nextjs:
    container_name: nextjs302_amazon_fe
    build:
      context: ..
      dockerfile: .docker_302/Dockerfile
    ports:
      - "6302:3000"
    volumes:
      - ../app:/usr/src/app
      - ../app/node_modules:/usr/src/app/node_modules
      - ../app/.next:/usr/src/app/.next
    environment:
      # Các biến môi trường để kết nối tới API của backend
      BACKEND_API_URL: http://nestjs_302_backend:3001
    networks:
      - nextjs302

networks:
  nextjs302:
    name: nextjs302 